version: '3.5'
services:
  terminalserver:
    build: ./
    image: ubuntu-xrdp:latest
    container_name: uxrdp
    hostname: terminalserver
    restart: always
    shm_size: 1g
    ports:
      - "3389:3389"
      - "2222:22"